/**
 * generated by Xtext 2.12.0
 */
package uk.ac.kcl.inf.mazegame.mazeGame;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Door Definition</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.inf.mazegame.mazeGame.DoorDefinition#getDirection <em>Direction</em>}</li>
 *   <li>{@link uk.ac.kcl.inf.mazegame.mazeGame.DoorDefinition#getAdjacentRoom <em>Adjacent Room</em>}</li>
 * </ul>
 *
 * @see uk.ac.kcl.inf.mazegame.mazeGame.MazeGamePackage#getDoorDefinition()
 * @model
 * @generated
 */
public interface DoorDefinition extends EObject
{
  /**
   * Returns the value of the '<em><b>Direction</b></em>' attribute.
   * The literals are from the enumeration {@link uk.ac.kcl.inf.mazegame.mazeGame.Direction}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Direction</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Direction</em>' attribute.
   * @see uk.ac.kcl.inf.mazegame.mazeGame.Direction
   * @see #setDirection(Direction)
   * @see uk.ac.kcl.inf.mazegame.mazeGame.MazeGamePackage#getDoorDefinition_Direction()
   * @model
   * @generated
   */
  Direction getDirection();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.mazegame.mazeGame.DoorDefinition#getDirection <em>Direction</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Direction</em>' attribute.
   * @see uk.ac.kcl.inf.mazegame.mazeGame.Direction
   * @see #getDirection()
   * @generated
   */
  void setDirection(Direction value);

  /**
   * Returns the value of the '<em><b>Adjacent Room</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Adjacent Room</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Adjacent Room</em>' reference.
   * @see #setAdjacentRoom(RoomDefinition)
   * @see uk.ac.kcl.inf.mazegame.mazeGame.MazeGamePackage#getDoorDefinition_AdjacentRoom()
   * @model
   * @generated
   */
  RoomDefinition getAdjacentRoom();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.mazegame.mazeGame.DoorDefinition#getAdjacentRoom <em>Adjacent Room</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Adjacent Room</em>' reference.
   * @see #getAdjacentRoom()
   * @generated
   */
  void setAdjacentRoom(RoomDefinition value);

} // DoorDefinition
