/**
 * generated by Xtext 2.12.0
 */
package uk.ac.kcl.inf.mazegame.mazeGame;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see uk.ac.kcl.inf.mazegame.mazeGame.MazeGameFactory
 * @model kind="package"
 * @generated
 */
public interface MazeGamePackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "mazeGame";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.ac.uk/kcl/inf/mazegame/MazeGame";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "mazeGame";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MazeGamePackage eINSTANCE = uk.ac.kcl.inf.mazegame.mazeGame.impl.MazeGamePackageImpl.init();

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.mazegame.mazeGame.impl.MazeGameImpl <em>Maze Game</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.mazegame.mazeGame.impl.MazeGameImpl
   * @see uk.ac.kcl.inf.mazegame.mazeGame.impl.MazeGamePackageImpl#getMazeGame()
   * @generated
   */
  int MAZE_GAME = 0;

  /**
   * The feature id for the '<em><b>Rooms</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAZE_GAME__ROOMS = 0;

  /**
   * The number of structural features of the '<em>Maze Game</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAZE_GAME_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.mazegame.mazeGame.impl.RoomDefinitionImpl <em>Room Definition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.mazegame.mazeGame.impl.RoomDefinitionImpl
   * @see uk.ac.kcl.inf.mazegame.mazeGame.impl.MazeGamePackageImpl#getRoomDefinition()
   * @generated
   */
  int ROOM_DEFINITION = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROOM_DEFINITION__NAME = 0;

  /**
   * The feature id for the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROOM_DEFINITION__DESCRIPTION = 1;

  /**
   * The feature id for the '<em><b>Doors</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROOM_DEFINITION__DOORS = 2;

  /**
   * The number of structural features of the '<em>Room Definition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROOM_DEFINITION_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.mazegame.mazeGame.impl.DoorDefinitionImpl <em>Door Definition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.mazegame.mazeGame.impl.DoorDefinitionImpl
   * @see uk.ac.kcl.inf.mazegame.mazeGame.impl.MazeGamePackageImpl#getDoorDefinition()
   * @generated
   */
  int DOOR_DEFINITION = 2;

  /**
   * The feature id for the '<em><b>Direction</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOOR_DEFINITION__DIRECTION = 0;

  /**
   * The feature id for the '<em><b>Adjacent Room</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOOR_DEFINITION__ADJACENT_ROOM = 1;

  /**
   * The number of structural features of the '<em>Door Definition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOOR_DEFINITION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.mazegame.mazeGame.Direction <em>Direction</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.mazegame.mazeGame.Direction
   * @see uk.ac.kcl.inf.mazegame.mazeGame.impl.MazeGamePackageImpl#getDirection()
   * @generated
   */
  int DIRECTION = 3;


  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.mazegame.mazeGame.MazeGame <em>Maze Game</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Maze Game</em>'.
   * @see uk.ac.kcl.inf.mazegame.mazeGame.MazeGame
   * @generated
   */
  EClass getMazeGame();

  /**
   * Returns the meta object for the containment reference list '{@link uk.ac.kcl.inf.mazegame.mazeGame.MazeGame#getRooms <em>Rooms</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Rooms</em>'.
   * @see uk.ac.kcl.inf.mazegame.mazeGame.MazeGame#getRooms()
   * @see #getMazeGame()
   * @generated
   */
  EReference getMazeGame_Rooms();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.mazegame.mazeGame.RoomDefinition <em>Room Definition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Room Definition</em>'.
   * @see uk.ac.kcl.inf.mazegame.mazeGame.RoomDefinition
   * @generated
   */
  EClass getRoomDefinition();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.inf.mazegame.mazeGame.RoomDefinition#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see uk.ac.kcl.inf.mazegame.mazeGame.RoomDefinition#getName()
   * @see #getRoomDefinition()
   * @generated
   */
  EAttribute getRoomDefinition_Name();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.inf.mazegame.mazeGame.RoomDefinition#getDescription <em>Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Description</em>'.
   * @see uk.ac.kcl.inf.mazegame.mazeGame.RoomDefinition#getDescription()
   * @see #getRoomDefinition()
   * @generated
   */
  EAttribute getRoomDefinition_Description();

  /**
   * Returns the meta object for the containment reference list '{@link uk.ac.kcl.inf.mazegame.mazeGame.RoomDefinition#getDoors <em>Doors</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Doors</em>'.
   * @see uk.ac.kcl.inf.mazegame.mazeGame.RoomDefinition#getDoors()
   * @see #getRoomDefinition()
   * @generated
   */
  EReference getRoomDefinition_Doors();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.mazegame.mazeGame.DoorDefinition <em>Door Definition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Door Definition</em>'.
   * @see uk.ac.kcl.inf.mazegame.mazeGame.DoorDefinition
   * @generated
   */
  EClass getDoorDefinition();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.inf.mazegame.mazeGame.DoorDefinition#getDirection <em>Direction</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Direction</em>'.
   * @see uk.ac.kcl.inf.mazegame.mazeGame.DoorDefinition#getDirection()
   * @see #getDoorDefinition()
   * @generated
   */
  EAttribute getDoorDefinition_Direction();

  /**
   * Returns the meta object for the reference '{@link uk.ac.kcl.inf.mazegame.mazeGame.DoorDefinition#getAdjacentRoom <em>Adjacent Room</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Adjacent Room</em>'.
   * @see uk.ac.kcl.inf.mazegame.mazeGame.DoorDefinition#getAdjacentRoom()
   * @see #getDoorDefinition()
   * @generated
   */
  EReference getDoorDefinition_AdjacentRoom();

  /**
   * Returns the meta object for enum '{@link uk.ac.kcl.inf.mazegame.mazeGame.Direction <em>Direction</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Direction</em>'.
   * @see uk.ac.kcl.inf.mazegame.mazeGame.Direction
   * @generated
   */
  EEnum getDirection();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  MazeGameFactory getMazeGameFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.mazegame.mazeGame.impl.MazeGameImpl <em>Maze Game</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.mazegame.mazeGame.impl.MazeGameImpl
     * @see uk.ac.kcl.inf.mazegame.mazeGame.impl.MazeGamePackageImpl#getMazeGame()
     * @generated
     */
    EClass MAZE_GAME = eINSTANCE.getMazeGame();

    /**
     * The meta object literal for the '<em><b>Rooms</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MAZE_GAME__ROOMS = eINSTANCE.getMazeGame_Rooms();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.mazegame.mazeGame.impl.RoomDefinitionImpl <em>Room Definition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.mazegame.mazeGame.impl.RoomDefinitionImpl
     * @see uk.ac.kcl.inf.mazegame.mazeGame.impl.MazeGamePackageImpl#getRoomDefinition()
     * @generated
     */
    EClass ROOM_DEFINITION = eINSTANCE.getRoomDefinition();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ROOM_DEFINITION__NAME = eINSTANCE.getRoomDefinition_Name();

    /**
     * The meta object literal for the '<em><b>Description</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ROOM_DEFINITION__DESCRIPTION = eINSTANCE.getRoomDefinition_Description();

    /**
     * The meta object literal for the '<em><b>Doors</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ROOM_DEFINITION__DOORS = eINSTANCE.getRoomDefinition_Doors();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.mazegame.mazeGame.impl.DoorDefinitionImpl <em>Door Definition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.mazegame.mazeGame.impl.DoorDefinitionImpl
     * @see uk.ac.kcl.inf.mazegame.mazeGame.impl.MazeGamePackageImpl#getDoorDefinition()
     * @generated
     */
    EClass DOOR_DEFINITION = eINSTANCE.getDoorDefinition();

    /**
     * The meta object literal for the '<em><b>Direction</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DOOR_DEFINITION__DIRECTION = eINSTANCE.getDoorDefinition_Direction();

    /**
     * The meta object literal for the '<em><b>Adjacent Room</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DOOR_DEFINITION__ADJACENT_ROOM = eINSTANCE.getDoorDefinition_AdjacentRoom();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.mazegame.mazeGame.Direction <em>Direction</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.mazegame.mazeGame.Direction
     * @see uk.ac.kcl.inf.mazegame.mazeGame.impl.MazeGamePackageImpl#getDirection()
     * @generated
     */
    EEnum DIRECTION = eINSTANCE.getDirection();

  }

} //MazeGamePackage
