/**
 * generated by Xtext 2.12.0
 */
package uk.ac.kcl.inf.mazegame.mazeGame;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see uk.ac.kcl.inf.mazegame.mazeGame.MazeGamePackage
 * @generated
 */
public interface MazeGameFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MazeGameFactory eINSTANCE = uk.ac.kcl.inf.mazegame.mazeGame.impl.MazeGameFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Maze Game</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Maze Game</em>'.
   * @generated
   */
  MazeGame createMazeGame();

  /**
   * Returns a new object of class '<em>Room Definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Room Definition</em>'.
   * @generated
   */
  RoomDefinition createRoomDefinition();

  /**
   * Returns a new object of class '<em>Door Definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Door Definition</em>'.
   * @generated
   */
  DoorDefinition createDoorDefinition();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  MazeGamePackage getMazeGamePackage();

} //MazeGameFactory
