/*
 * generated by Xtext 2.12.0
 */
package uk.ac.kcl.inf.mazegame.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import uk.ac.kcl.inf.mazegame.xtext.ui.internal.XtextActivator;

public class MazeGameUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return XtextActivator.getInstance().getInjector("uk.ac.kcl.inf.mazegame.MazeGame");
	}

}
