/*
 * generated by Xtext 2.12.0
 */
package uk.ac.kcl.inf.mazegame.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractMazeGameScopeProvider extends DelegatingScopeProvider {
}
