/*
 * generated by Xtext 2.12.0
 */
package uk.ac.kcl.inf.mazegame.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class MazeGameAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("uk/ac/kcl/inf/mazegame/parser/antlr/internal/InternalMazeGame.tokens");
	}
}
