/*
 * generated by Xtext 2.12.0
 */
package uk.ac.kcl.inf.mazegame.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import uk.ac.kcl.inf.mazegame.parser.antlr.internal.InternalMazeGameParser;
import uk.ac.kcl.inf.mazegame.services.MazeGameGrammarAccess;

public class MazeGameParser extends AbstractAntlrParser {

	@Inject
	private MazeGameGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalMazeGameParser createParser(XtextTokenStream stream) {
		return new InternalMazeGameParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "MazeGame";
	}

	public MazeGameGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MazeGameGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
