/*
 * generated by Xtext 2.12.0
 */
package uk.ac.kcl.inf.mazegame.ide


/**
 * Use this class to register ide components.
 */
class MazeGameIdeModule extends AbstractMazeGameIdeModule {
}
